ACPA_Lab02/Models/CustomerModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ACPA_Lab02.Models
{
	public class CustomerModel
	{
		public string id { get; set; }
		public string nombre { get; set; }
		public string descripcion { get; set; }
		public string productora{ get; set; }
		public string precio { get; set; }
		public string existencia { get; set; }

}
}

ACPA_Lab02/Models/Medicamento.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Collections;
using ACPA_Lab02.Helpers;


namespace ACPA_Lab02.Models
{
	public class Medicamento : IComparable, IEnumerable
	{
		[Display(Name = "Id")]
		public int id { get; set; }
		[Display(Name = "Nombre")]
		public string nombre { get; set; }
		[Display(Name = "Descripción")]
		public string descripcion { get; set; }
		[Display(Name = "Productora")]
		public string productora { get; set; }
		[Display(Name = "Precio")]
		public double precio { get; set; }
		[Display(Name = "Existencia")]
		public int existencia { get; set; }

		public int CompareTo(object obj)
		{
			var comparador = (Medicamento)obj;
			return nombre.CompareTo(comparador.id);
		}
		public IEnumerator GetEnumerator()
		{
			throw new NotImplementedException();
		}
	}
}

ACPA_Lab02/Models/Pedido.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Collections;
using ACPA_Lab02.Helpers;

namespace ACPA_Lab02.Models
{
	public class Pedido : IComparable, IEnumerable
	{
		[Display(Name = "Id")]
		public int idc { get; set; }

		[Display(Name = "Nombre")]
		public string cliente { get; set; }

		[Display(Name = "Nit")]
		public string nit { get; set; }

		[Display(Name = "Descripcion")]
		public string detalle { get; set; }

		[Display(Name = "Total")]
		public double total { get; set; }

		[Display(Name = "Fecha"), DataType(DataType.Time)]
		public DateTime fecha { get; set; }
		
		public int CompareTo(object obj)
		{
			var comparador = (Pedido)obj;
			return cliente.CompareTo(comparador.idc);
		}
		public IEnumerator GetEnumerator()
		{
			throw new NotImplementedException();
		}
	}
}

ACPA_Lab02/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ACPA_Lab02.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}

		public ActionResult About()
		{
			ViewBag.Message = "Your application description page.";

			return View();
		}

		public ActionResult Contact()
		{
			ViewBag.Message = "Your contact page.";

			return View();
		}

	}
}

ACPA_Lab02/Controllers/InfoController.cs
using ACPA_Lab02.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace ACPA_Lab02.Controllers
{
    public class InfoController : Controller
    {

		public ActionResult Menu()
		{
			return View();
		}
		public ActionResult Pedido()
		{
			return View();
		}
		public ActionResult Orden ()
		{
			return View();
		}
		public ActionResult Restablecer()
		{
			return View();
		}
        // GET: Info
        public ActionResult Index()
        {
            return View(new List<CustomerModel>());
        }
		[HttpPost]
		public ActionResult Index(HttpPostedFileBase postedFile)
		{
			List<CustomerModel> customers = new List<CustomerModel>();
			string filePath = string.Empty;
			if (postedFile != null)
			{
				string path = Server.MapPath("~/Uploads/");
				if (!Directory.Exists(path))
				{
					Directory.CreateDirectory(path);
				}
				filePath = path + Path.GetFileName(postedFile.FileName);
				string extension = Path.GetExtension(postedFile.FileName);
				postedFile.SaveAs(filePath);

				string csvData = System.IO.File.ReadAllText(filePath);
				foreach(string row in csvData.Split('\n'))
				{
					if (!string.IsNullOrEmpty(row))
					{
						customers.Add(new CustomerModel
						{
							id = row.Split(',')[0],
							nombre = row.Split(',')[1],
							descripcion = row.Split(',')[2],
							productora = row.Split(',')[3],
							precio = row.Split(',')[4],
							existencia = row.Split(',')[5],
						});
					}
				}
			}
			return View(customers);
		}
    }
}

ACPA_Lab02/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ACPA_Lab02/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ACPA_Lab02/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
	<h2>Farmacia Hipócrates</h2>
	<p><a href="https://principal.url.edu.gt/" class="btn btn-primary btn-lg"> Subir Data &uarr;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ACPA_Lab02/Views/Info/Index.cshtml
@using ACPA_Lab02.Models;
@model IEnumerable<CustomerModel>


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
	<h2>Seleccione un archivo</h2>
	<style type="text/css">
		body{
			font-family: Arial;
			font-size: 12pt;
		}
		table{
			border: 3px solid #ccc;
			border-collapse: collapse;
			background-color: #fff;
		}
		table th{
			background-color: #B8DBFD;
			color: #333;
			font-weight: bold;
		}
		table, table table td{
			border: 0px solid #000000;
		}
	</style>
</head>
<body>
	@using (Html.BeginForm("Index", "Info", FormMethod.Post, new { enctype = "multipart/form-data" }))
	{
		<input type="file" name="postedFile" />
		<input type="submit" value="Importar" />
		<li>@Html.ActionLink("Menu", "Menu", "Info")</li>
	}

	@if (Model.Count() > 0)
	{
		<hr />
		<table cellpadding="0" cellspacing="0">
			<tr>
				<th>Id</th>
				<th>Nombre</th>
				<th>Descripcion</th>
				<th>Productora</th>
				<th>Precio</th>
				<th>Existencia</th>
			</tr>
			@foreach (CustomerModel customer in Model)
			{
				<tr>
					<td>@customer.id</td>
					<td>@customer.nombre</td>
					<td>@customer.descripcion</td>
					<td>@customer.productora</td>
					<td>@customer.precio</td>
					<td>@customer.existencia</td>
				</tr>
			}
		</table>
	}
</body>
</html>

ACPA_Lab02/Views/Info/Menu.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Menu</title>
</head>
<body>
	<h2>Menú</h2>
	<div>
		<li>@Html.ActionLink("Crear pedido", "Pedido", "Info")</li>
		<li>@Html.ActionLink("Ordenar", "Orden", "Info")</li>
		<li>@Html.ActionLink("Restablecer", "Restablecer", "Info")</li>
	</div>
</body>
</html>

ACPA_Lab02/Views/Info/Orden.cshtml
<h2>Seleccione una opción para ordenar</h2>

@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

<div class="form-horizontal">
	<hr />

	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<input type="submit" value="PreOrden" class="btn btn-default" />
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<input type="submit" value="InOrden" class="btn btn-default" />
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<input type="submit" value="PostOrden" class="btn btn-default" />
		</div>
	</div>
</div>
}
<div>
	@Html.ActionLink("Regresar", "Menu")
</div>
@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

ACPA_Lab02/Views/Info/Pedido.cshtml
@model ACPA_Lab02.Models.Pedido
<h2>Ingresar Informacion del Pedido</h2>

@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

<div class="form-horizontal">
	<h4>Farmacia Hipócrates</h4>
	<hr />
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
	<div class="form-group">
		@Html.LabelFor(model => model.idc, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.idc, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.idc, "", new { @class = "text-danger" })
		</div>
	</div>
	<div class="form-group">
		@Html.LabelFor(model => model.cliente, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.cliente, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.cliente, "", new { @class = "text-danger" })
		</div>
	</div>
	<div class="form-group">
		@Html.LabelFor(model => model.nit, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.nit, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.nit, "", new { @class = "text-danger" })
		</div>
	</div>
	<div class="form-group">
		@Html.LabelFor(model => model.detalle, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.detalle, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.detalle, "", new { @class = "text-danger" })
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-offset-3 col-md-10">
			<input type="submit" value="Cotizar" class="btn btn-default" />
		</div>
	</div>
	<div class="form-group">
		@Html.LabelFor(model => model.total, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.total, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.total, "", new { @class = "text-danger" })
		</div>
	</div>
	<div class="form-group">
		@Html.LabelFor(model => model.fecha, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.fecha, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
		</div>
	</div>
	<div class="form-group">
		<div class="col-md-offset-3 col-md-10">
			<input type="submit" value="Guardar" class="btn btn-default" />
		</div>
	</div>
</div>
}
<div>
	@Html.ActionLink("Regresar", "Menu")
</div>
@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

ACPA_Lab02/Views/Info/Restablecer.cshtml
@model ACPA_Lab02.Models.Medicamento
<h2>Listado de medicamentos con 0 existencia</h2>

@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			<div class="col-md-offset-3 col-md-10">
				<input type="submit" value="Abastecer" class="btn btn-default" />
			</div>
		</div>
	</div>
}
<div>
	@Html.ActionLink("Regresar", "Menu")
</div>
@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

ACPA_Lab02/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Farmacia Hipócrates S. A.</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-prev"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
				<h2>Farmacia Hipocrates</h2>
               @* @Html.ActionLink("Farmacia Hipócrates S. A.", "Menu", "Farmacia", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					@*<li>@Html.ActionLink("Inicio", "SubirInfo", "Farmacia")</li>
					<li>@Html.ActionLink("Acerca de", "About", "Home")</li>
		<li>@Html.ActionLink("Contacto", "Contact", "Home")</li>*@
				</ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Farmacia Hipocrates</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>